name: lightning_overlay
description: >
  Add a beautiful, animated lightning overlay effect to any Flutter widget — 
  like Skeletonizer but without background or shimmer effects.
version: 1.0.1
homepage: https://github.com/Gastrolize/lightning_overlay
repository: https://github.com/Gastrolize/lightning_overlay
issue_tracker: https://github.com/Gastrolize/lightning_overlay/issues

keywords:
  - flutter
  - overlay
  - animation
  - lightning
  - effect
  - shimmer
  - highlight
  - widget
  - light
  - beam
  - glow
  - visual effect
  - ui effect

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
