name: lightning_overlay
description: Create nice Overlay Effect on any of your Widgets
version: 0.0.1
homepage: https://github.com/Gastrolize/lightning_overlay

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

